### ISSUE TITLE
Remove chances are sentence. It doesnt add to the message and is redundant with the following sentence.

### ISSUE THREAD

**Issue by emdecr** [hypenotic/harris-affinity#19]
[Task](https://app.trackduck.com/project/5b324b424e659e3465d71e76/issue/5b3458d94e659e3465d72a39?utm_source=integration&utm_medium=app_github&utm_content=task) with ***Low*** priority was created by ***zmorton@harriscomputer.com***:

>Remove chances are sentence. It doesnt add to the message and is redundant with the following sentence.

[![Issue screenshot](https://app.trackduck.com/file/crop/5b324b424e659e3465d71e76-1530157224774-311-452.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)](https://app.trackduck.com/preview/awsi/5b324b424e659e3465d71e76-1530157224774-311-452.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)

Environment: ***Mobile Safari 11*** on ***iOS*** with ***320x207*** screen size.

Check it in your [website](http://dev.hypenotic.com/harris-affinity/product/aerp/?tdtask=5b3458d94e659e3465d72a39) or get [more details...](https://app.trackduck.com/project/5b324b424e659e3465d71e76/issue/5b3458d94e659e3465d72a39?utm_source=integration&utm_medium=app_github&utm_content=task)

**Comment by barrymartin** [comment]
Actually, I like that line, but it’s missing the word “job” after “one”. As in “one job”

Barry A. Martin, Principal
HYPENOTIC, Persuasion by Design
t. 416-363-5215 |  m. 416-575.9994 | twitter. @hypenoticbam
www.hypenotic.com | Proud to be B Corporation Certified

**Comment by emdecr** [comment]
__jen phelan__:
>added 'job'
