### ISSUE TITLE
On mobile, Mac drops down half off the screen

### ISSUE THREAD

**Issue by emdecr** [hypenotic/harris-affinity#24]
[Task](https://app.trackduck.com/project/5b324b424e659e3465d71e76/issue/5b34cbd194cf14512d43e46b?utm_source=integration&utm_medium=app_github&utm_content=task) with ***Low*** priority was created by ***anonymous user***:

>On mobile, Mac drops down half off the screen

[![Issue screenshot](https://app.trackduck.com/file/crop/5b324b424e659e3465d71e76-1530186679634-366-626.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)](https://app.trackduck.com/preview/awsi/5b324b424e659e3465d71e76-1530186679634-366-626.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)

Environment: ***Mobile Safari 11*** on ***iOS*** with ***375x635*** screen size.

Check it in your [website](http://dev.hypenotic.com/harris-affinity/?tdtask=5b34cbd194cf14512d43e46b) or get [more details...](https://app.trackduck.com/project/5b324b424e659e3465d71e76/issue/5b34cbd194cf14512d43e46b?utm_source=integration&utm_medium=app_github&utm_content=task)

**Comment by barrymartin** [comment]
Sorry, that was supposed to say NAV

Barry A. Martin, Principal
HYPENOTIC, Persuasion by Design
t. 416-363-5215 |  m. 416-575.9994 | twitter. @hypenoticbam
www.hypenotic.com | Proud to be B Corporation Certified
